- name: Run Fabric states validation
  hosts: FABRIC
  tasks:
    - name: Deploy configuration to device
      ansible.builtin.import_role:
        name: arista.avd.eos_validate_state
      vars:
        use_anta: true
        save_catalog: true
