---
servers:
  - name: host1
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ leaf1, leaf2 ]
        vlans: 10
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: PortChannel host1
          mode: active
  - name: host2
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet9, Ethernet9 ]
        switches: [ leaf1, leaf2 ]
        vlans: 20
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: PortChannel host2
          mode: active
  - name: host3
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ leaf3, leaf4 ]
        vlans: 30
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: PortChannel host3
          mode: active 
          short_esi: 0303:0202:0101
  - name: host4
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet9, Ethernet9 ]
        switches: [ leaf3, leaf4 ]
        vlans: 40
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: PortChannel host4
          mode: active 
          short_esi: 0303:0202:0101
  # - name: host3
  #   adapters:
  #     - endpoint_ports: [ Ethernet1 ]
  #       switch_ports: [ Ethernet7 ]
  #       switches: [ leaf3 ]
  #       vlans: 30
  #       mode: access
  #       spanning_tree_portfast: edge
  # - name: host4
  #   adapters:
  #     - endpoint_ports: [ Ethernet1 ]
  #       switch_ports: [ Ethernet9 ]
  #       switches: [ leaf4 ]
  #       vlans: 40
  #       mode: access
  #       spanning_tree_portfast: edge
        