---
- name: Add VLANs to device(s)
  hosts: leafs
  tasks:
    - name: Add VLANS
      arista.eos.eos_vlans:
        config:
          - vlan_id: 10
            name: "DMZ"
            state: active
          - vlan_id: 20
            name: "Internal"
            state: active
        state: merged
      
