---
- name: Add VLANs to device(s)
  hosts: leafs
  tasks:
    - name: Add VLANS
      arista.eos.eos_vlans:
        config:
          - vlan_id: "{{ item['id'] }}"
            name: "{{ item['name'] }}"
            state: "{{ item['state'] }}"
        state: merged
      loop: "{{ global_vlans }}"
