---

- name: Recreate the Leaf1 Config Playbook
  hosts: leaf1
  vars_files:
    - group_vars/neil.yml
  tasks:
    - name: Add a banner to Leaf1 
      arista.eos.eos_config:
        lines:
          - hostname NEIL
          - no banner motd
          - banner motd
          - Hello_world1
          - EOF
        replace: block