---

- name: Test playbook for syntax experience
  hosts: leaf1
  vars_files:
    - group_vars/neil.yml
  tasks:
    - name: load an acl into the device
      arista.eos.eos_config:
        lines:
          - hostname NEIL
          - no banner motd
          - banner motd
          - Hello_world1
          - EOF
        replace: line