---
- name: Playbook for moving borderleaf1 to a different container in CloudVision
  hosts: cvp1

  vars_files:
    - ../vars/CVP_model.yml

  tasks:
    - name: Apply configlets to devices
      arista.cvp.cv_device_v3:
        devices: "{{ CVP_DEVICES_BL }}"
        state: present
        apply_mode: loose

    - name: Grab and register facts
      arista.cvp.cv_facts_v3:
        facts: 
          - tasks
        regexp_filter: 'Pending'
      register: CVP_FACTS
    - name: Run pending tasks
      arista.cvp.cv_task_v3:
        tasks: "{{ CVP_FACTS.data.cvp_tasks | list }}"